version: '3'

services:

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ../../db/postgres:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.24
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: prisma 
      PGADMIN_DEFAULT_PASSWORD: prisma
    volumes:
       - ../../db/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

# Favoring directories for now
# volumes:
#   postgres:
#   pgadmin:
